name: Build All Microservices

on:
  workflow_dispatch:  # manually trigger OR replace with "push:" to trigger on push

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push all services with Dockerfile
        run: |
         for dir in ./src/*; do
         if [ -f "$dir/Dockerfile" ]; then
         service=$(basename "$dir")
          echo "Building $service..."
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/otel/$service:${{ github.sha }} . --file $dir/Dockerfile
          docker push ${{ secrets.DOCKER_REGISTRY }}/otel/$service:${{ github.sha }}
          else
          echo "Skipping $(basename "$dir") (no Dockerfile)"
          fi
         done

