name: Simple Docker Build

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push to Docker Hub?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      image_name:
        description: 'Image name (e.g., my-app)'
        required: true
      dockerfile_dir:
        description: 'Directory of Dockerfile (e.g., ./src/my-app)'
        required: true
      docker_tag:
        description: 'Tag (e.g., v1)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (if push is true)
        if: ${{ github.event.inputs.push == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
         - name: Build Docker Image
         docker build -f src/accounting/Dockerfile -t accounting .



      - name: Push Docker Image (if push is true)
        if: ${{ github.event.inputs.push == 'true' }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.docker_tag }}
